// AUTO-GENERATED by tools/gen_gaps.mjs — do not edit by hand.
// Feeds the studio's "Needs art" hub (studio/js/pages/needs-art.js) and, once
// pushed with --push, server/src/workshop.js's PixelLab auto-accept lane —
// a generation that fills one of these subjects skips voting and ships
// straight into the community layer.
"use strict";
const WORKSHOP_GAPS = {"generated":"2026-09-29T03:30:19.787Z","gaps":[{"subject":"gen:monster:slime","type":"monster","key":"slime","name":"Slime","reason":"has one sprite, needs 8-direction art"},{"subject":"gen:monster:troll","type":"monster","key":"troll","name":"Cave Troll","reason":"has one sprite, needs 8-direction art"},{"subject":"gen:monster:bandit","type":"monster","key":"bandit","name":"Bandit","reason":"has one sprite, needs 8-direction art"}]};
