// ===== Our RPG Workshop — offline prompt / sprite_id suggestions =====
// Backs the "Suggest a prompt" button in every sprite-generation dialogue
// (studio/js/genjobs.js). No network call, no API key: a hand-written bank
// of PixelLab-ready prompts per sprite kind, picked at random (never the
// same one twice in a row), plus a large combinatorial pool of themed
// sprite_ids checked against whatever's already taken.
"use strict";

const PromptBank = (function () {
  const PROMPTS = {
    character: [
      "a weathered fern-cloaked ranger with a carved wooden staff and a satchel of dried herbs",
      "a young apprentice smith with soot-streaked forearms and a leather apron",
      "a barefoot river guide with a coil of flax rope slung over one shoulder",
      "a hooded night-watch scout wearing a dark oilskin cloak, bow on their back",
      "a cheerful market trader in a patched wool coat, arms full of woven baskets",
      "a weary long-road courier with dusty boots and a bundle of sealed letters",
      "a bright-eyed fledgling healer carrying a satchel of jars and bandages",
      "a stout dockhand with rolled sleeves and a heavy coil of rope over one arm",
      "a quiet forest warden in moss-green leathers, a hand axe at their belt",
      "a travelling storyteller in a patchwork cloak hung with small bells",
      "a proud gate guard in dented bronze plate, spear held at ease",
      "a barefoot tide-pool forager with a woven kete full of shellfish",
      "a grizzled old prospector with a pickaxe and a battered tin pan",
      "a nimble rooftop courier in tight dark leathers and soft-soled boots",
      "a solemn shrine keeper wrapped in a pale woven cloak, holding a small lantern",
      "a boisterous tavern cook with a stained apron and a ladle tucked in their belt",
      "a young falconer with a leather gauntlet and a hooded bird on one arm",
      "a wandering herbalist with bundles of dried plants tied to their pack",
      "a scarred veteran mercenary in mismatched armour, a notched sword on their hip",
      "a shy apprentice mage in an oversized robe, clutching a cracked spellbook",
      "a river ferryman in patched oilcloth, leaning on a long wooden pole",
      "a determined shepherd with a crook and a coil of rope, mud on their boots",
      "a masked bandit in dark wraps, twin daggers sheathed at each hip",
      "a cheerful bee-keeper in a wide straw hat and thick canvas gloves",
      "a bookish scribe with ink-stained fingers and a satchel of scrolls",
      "a mountain guide bundled in thick furs, an ice axe strapped to their pack",
      "a young stablehand with hay in their hair and a horseshoe in one hand",
      "a wandering minstrel with a battered lute slung across their back",
      "a stern city watch captain in polished plate with a fern-leaf crest",
      "a barefoot beachcomber wrapped in a faded sarong, a net over one shoulder",
      "a nervous new recruit in ill-fitting armour, gripping a spear too tightly",
      "a leathery old sailor with a coil of tarred rope and a hooked pipe",
      "a fierce warrior chief in a feathered cloak, greenstone club in hand",
      "a soft-spoken potter with clay-caked hands and a rolled leather toolkit",
      "a sharp-eyed bounty hunter in dark travelling leathers, crossbow on their back",
      "a gentle grove-tender in pale linen, a watering can in each hand",
      "a bold young duelist with a rapier and a torn silk sash",
      "a weathered lighthouse keeper in a heavy oilskin coat, lantern in hand",
      "a curious young inventor with goggles pushed up and grease-stained gloves",
      "a solemn temple guardian in carved wooden armour, twin clubs at the ready",
      "a travelling tinker with pots and pans hanging from a heavy backpack",
      "a wiry cave prospector with a lantern helmet and a coil of climbing rope",
      "a proud reef diver in a woven vest, a bone-handled knife at their thigh",
      "a hardened frontier trapper wrapped in furs, a string of snares on their belt",
      "a graceful court dancer in a flowing feathered gown",
      "a stubborn old farmer in patched overalls, a scythe over one shoulder",
      "a keen-eyed archer in fern-green leathers, quiver bristling with arrows",
      "a weary night-shift lamplighter with a long brass pole and a satchel of oil",
      "a mysterious hooded traveller wrapped in a grey cloak, face in shadow",
      "a jovial harbourmaster in a brass-buttoned coat, spyglass in hand",
    ],
    "monster:humanoid": [
      "a hulking swamp brute with mossy grey skin and a crude wooden club",
      "a gaunt cave-dwelling stalker with pale eyes and long clawed fingers",
      "a snarling bandit thug in scavenged leather armour, notched axe in hand",
      "a hunched bog witch wrapped in tattered rags, a gnarled staff in hand",
      "a towering stone-skinned golem with cracked lichen-covered limbs",
      "a wiry goblin skirmisher clutching a crooked dagger and a stolen shield",
      "a rotting bog zombie draped in waterlogged cloth, arms outstretched",
      "a horned tribal raider in bone jewellery, twin hatchets raised",
      "a spindly shadow-wraith with smoky trailing limbs and glowing eyes",
      "a barrel-chested ogre with a spiked club slung over one shoulder",
      "a masked cultist in dark robes, a curved ritual blade in hand",
      "a feral wildling hunter draped in animal pelts, a bone spear in hand",
      "a crooked hag with long tangled hair and grasping, twig-like fingers",
      "a brutish troll with knuckle-dragging arms and a boulder for a club",
      "a skeletal warrior in rusted plate, wielding a chipped broadsword",
      "a fungal-crusted forest lurker with moss growing from its shoulders",
      "a fanged frost raider bundled in icy furs, a jagged axe in hand",
      "a hunched tunnel digger with oversized claws and dirt-caked hide",
      "a smouldering ember-wraith wreathed in faint orange smoke",
      "a scarred pit-fighter in spiked leather harness, chains around one fist",
      "a slick-skinned marsh stalker with webbed hands and a barbed spear",
      "a towering armoured sentinel built from riveted scrap plate",
      "a wailing banshee-like spirit trailing tattered white cloth",
      "a squat cave troll gnawing on a splintered bone club",
      "a masked executioner in a heavy leather hood, a broad axe resting on one shoulder",
      "a thorny bramble-golem with vines knotted into a rough humanoid shape",
      "a rasping plague-marked wanderer wrapped in stained bandages",
      "a fierce highland raider in furs and iron studs, a war-hammer in hand",
      "a slouched grave-robber in a patched coat, a pickaxe over one shoulder",
      "a crackling storm-touched shaman crackling with faint blue sparks",
      "a lumbering sack-headed scarecrow guardian stuffed with straw",
      "a sunken-eyed drowned sailor dripping with kelp and barnacles",
      "a squat cavern miner-turned-monster with a pickaxe fused to one arm",
      "a snarling pit hound handler cloaked in chains and dark leather",
      "a molten-cracked ember golem glowing faintly along its seams",
      "a robed necromancer's thrall shuffling with jerky, puppet-like steps",
      "a horned minotaur-like brute with a heavy iron ring through its nose",
      "a spiny quill-backed hermit crouched low, bone dagger clenched tight",
      "a rusted clockwork sentinel missing half its armour plating",
      "a howling wind-spirit given rough human shape from swirling leaves",
    ],
    "monster:quadruped": [
      "a mangy swamp wolf with matted fur and glowing yellow eyes",
      "a hulking wild boar with cracked tusks and a scarred hide",
      "a sleek river eel-hound with slick dark scales and a whip-like tail",
      "a shaggy highland ram with thick curling horns and a stormy grey coat",
      "a lean cave lynx with tufted ears and pale luminous eyes",
      "a stocky armoured tortoise with a cracked, moss-covered shell",
      "a wiry desert jackal with sun-bleached fur and a low, hungry gait",
      "a hulking cave bear with matted black fur and long ragged claws",
      "a spindly-legged marsh stalker with a heron-like beak and webbed feet",
      "a scaled swamp lizard with a ridged spine and a low, wide stance",
      "a shaggy pack hound with a studded leather collar and bared fangs",
      "a horned forest stag with unnaturally sharp, jagged antlers",
      "a squat rooting boar-hog with tusks crusted in dried mud",
      "a sleek nocturnal fox with oversized ears and a glossy black coat",
      "a bristling porcupine-like beast with long dark quills along its back",
      "a lumbering ox-like brute with a heavy iron yoke fused to its shoulders",
      "a slinking shadow-cat with a smoky, half-translucent tail",
      "a hardy mountain goat with cracked hooves and a shaggy grey coat",
      "a snapping bog crocodile with algae clinging to its ridged back",
      "a lanky plains runner with long thin legs and a striped hide",
      "a hulking rhino-like brute with a cracked, weathered horn",
      "a feral pack wolf with a torn ear and a low, rumbling growl",
      "a spiny cave crawler with too many legs and clicking mandibles",
      "a stout badger-like digger with sharp claws and a striped face",
      "a wiry hyena-like scavenger with a mottled hide and a manic grin",
      "a hulking woolly beast with thick matted fur and small curved tusks",
      "a sleek otter-like river hunter with slick fur and webbed paws",
      "a horned bull with a scarred hide and a ring through its nose",
      "a squat toad-like brute with warty skin and a wide, croaking mouth",
      "a lean greyhound-like courser bred for speed, ribs faintly visible",
      "a hulking armoured beetle-beast with a segmented plated shell",
      "a shaggy mountain wolf with frost clinging to its whiskers",
      "a sinuous marsh serpent with a frilled hood and dull green scales",
      "a stocky wild pony with a tangled mane and mud-caked fetlocks",
      "a clawed burrowing mole-beast with tiny eyes and huge front paws",
      "a spiked quill-boar with a bristling ridge of hardened spines",
      "a lanky camel-like pack beast with a battered saddle still strapped on",
      "a low-slung crocodile-hound hybrid with a bony ridged back",
      "a mottled grey wildcat with tufted paws and a low hunting crouch",
      "a hulking cave ram with thick curled horns scarred from fighting",
    ],
    object: [
      "a weathered wooden anvil stump with a chipped iron cap",
      "a woven flax storage basket overflowing with dried herbs",
      "a moss-covered stone well with a cracked wooden bucket",
      "a rickety market stall awning, faded canvas flapping loose",
      "a squat clay kiln with soot-blackened vents",
      "a carved wooden totem post wrapped in fading ribbons",
      "a rusted iron ship's anchor half-buried in sand",
      "a weathered rowboat with a cracked hull, resting on a bank",
      "a small stone shrine with a bundle of dried flowers at its base",
      "a driftwood signpost with a crooked carved arrow",
      "a barrel-stacked cellar door, hinges thick with rust",
      "a low garden fence woven from flax and thin branches",
      "a stone geothermal vent ringed with mineral-crusted rock",
      "a leaning wooden watchtower ladder, rungs worn smooth",
      "a small wooden footbridge over a narrow stream",
      "a cracked ceramic water urn wrapped in twine",
      "a weathered fishing net drying on a wooden rack",
      "a squat blacksmith's bellows beside a cold forge",
      "a carved stone bench beneath a leaning tree",
      "a rusted iron lantern post with a cracked glass pane",
      "a heavy wooden portcullis winch, chain wound tight",
      "a woven reed mat rolled beside a low doorway",
      "a mossy stepping-stone path across a shallow pond",
      "a battered wheelbarrow half-full of loose stone",
      "a hanging wind chime made from strung shells and bone",
      "a small stone cairn stacked with smooth river rocks",
      "a wooden loom strung with half-finished cloth",
      "a squat rain barrel with a curled wooden spout",
      "a leaning scarecrow stuffed with straw, hat askew",
      "a low stone firepit ringed with blackened rocks",
      "a wooden ladder propped against a mossy stone wall",
      "a rusted iron gate, bars bent and vines creeping through",
      "a driftwood beach shelter propped with old sailcloth",
      "a carved wooden canoe resting on a rack near the shore",
      "a small apiary of stacked wooden beehive boxes",
      "a cracked millstone half-sunk into the grass",
      "a weathered wooden pier post with a coiled rope",
      "a stone sundial worn smooth by rain and moss",
      "a hanging string of dried chillies and herbs by a doorway",
      "a squat root cellar hatch set into a grassy mound",
      "a rickety rope bridge slung between two rocky outcrops",
      "a stack of woven wool blankets on a wooden bench",
      "a battered iron cooking pot hung over a cold hearth",
      "a small wooden dovecote mounted on a tilted post",
      "a stone boundary marker etched with a spiral pattern",
      "a leaning market cart loaded with crates of vegetables",
      "a weathered ship's figurehead propped against a dock wall",
      "a carved wooden hitching post with a looped leather rein",
      "a squat charcoal kiln mound, smoke curling from its vent",
      "a low drystone wall with a gap for a wooden stile",
    ],
    item: [
      "a polished greenstone pendant on a braided cord",
      "a small vial of glowing blue liquid, corked with wax",
      "a chipped stone hand-axe with a leather-wrapped grip",
      "a folded woven flax cloak, soft and tightly bound",
      "a battered brass compass with a cracked glass face",
      "a small leather coin pouch, drawstring pulled tight",
      "a curved bone fishhook tied with fine cord",
      "a sealed clay jar of dark honey with a wax stopper",
      "a hand-carved wooden flute with faint spiral markings",
      "a rolled parchment map tied with a red ribbon",
      "a rusted iron key on a worn leather loop",
      "a small pouch of dried medicinal herbs, tightly cinched",
      "a polished obsidian arrowhead, edges sharp and glossy",
      "a woven grass sun hat with a frayed brim",
      "a tiny glass jar of shimmering firefly dust",
      "a carved bone whistle strung on a thin cord",
      "a chipped ceramic teacup with a faded painted pattern",
      "a coil of thin braided fishing line on a wooden spool",
      "a small tin of dark boot polish, lid slightly dented",
      "a folded oilskin rain cape, waxy and worn at the seams",
      "a single carved wooden chess piece, a rearing horse",
      "a battered tin lantern with a stub of candle inside",
      "a smooth river stone painted with a small spiral rune",
      "a woven friendship bracelet in faded green and gold thread",
      "a chipped stone mortar and pestle stained with herb dust",
      "a small brass bell on a leather thong, slightly tarnished",
      "a folded letter sealed with a blob of red wax",
      "a hand-stitched leather pouch of polished marbles",
      "a curved horn drinking cup rimmed with tarnished silver",
      "a bundle of dried lavender tied with twine",
      "a small brass pocket sundial, hinge squeaking with age",
      "a chipped wooden top, paint worn thin from spinning",
      "a coil of thin copper wire looped around a wooden peg",
      "a small woven basket of speckled quail eggs",
      "a folded canvas satchel with a rusted brass buckle",
      "a smooth whalebone hairpin carved with a fern motif",
      "a tiny glass bottle of shimmering silver sand",
      "a battered brass whistle on a frayed cord",
      "a small stack of pressed fern leaves tied with string",
      "a chipped clay whistle shaped like a small bird",
    ],
    state: [
      "wearing a weathered oilskin coat, hood up against the rain",
      "battle-worn, scratched armour and a fresh bandage wrapped tight",
      "dressed for a festival, bright ribbons and a flower crown",
      "muddy from the fields, boots and hem caked in dried earth",
      "wrapped in a thick winter cloak with frost on the collar",
      "scorched and soot-streaked, as if just escaped a fire",
      "dripping wet, hair plastered down after a swim",
      "dressed in fine formal wear for a feast, polished and pressed",
      "sun-bleached and travel-worn after a long desert crossing",
      "bundled in heavy furs for a snowbound mountain trek",
      "dusty from the road, a wide-brimmed hat pulled low",
      "dressed for night duty, dark cloak and a shuttered lantern",
      "freshly bandaged after a rough tumble, a slight limp",
      "decked out for a celebration, streamers and a paper crown",
      "soaked through from a sudden storm, cloak clinging heavy",
      "dressed in mourning black, a single white flower pinned on",
      "covered in flour and dusted with sugar from the kitchen",
      "geared up for battle, fresh polish on newly forged armour",
      "wrapped in a light summer wrap, sandals and a sunhat",
      "camouflaged in leafy scout gear for a stealth mission",
      "dressed formally for a court audience, a fine cloak pinned at the shoulder",
      "grubby and singed from a workshop mishap",
      "wearing ceremonial regalia trimmed with feathers",
      "bandaged head to toe after a rough sea voyage",
      "dressed for the hunt, quiver full and boots freshly oiled",
      "shivering, a thin blanket clutched around bare shoulders",
      "dressed in armoured diving gear, a coil of rope at the hip",
      "wearing a patched apprentice's smock stained with dye",
      "geared for a climb, ropes and pitons clipped to a harness",
      "dressed for a masquerade, an ornate carved half-mask",
    ],
    state_ids: [
      "armed", "winter_cloak", "battle_worn", "festival_dress", "muddy",
      "scorched", "drenched", "formal_attire", "sun_bleached", "furs",
      "dusty_road", "night_watch", "bandaged", "celebration", "storm_soaked",
      "mourning", "kitchen_mess", "freshly_forged", "summer_wrap", "camouflaged",
      "court_dress", "workshop_mishap", "ceremonial", "sea_worn", "hunting_gear",
      "shivering", "diving_gear", "apprentice_smock", "climbing_gear", "masquerade",
    ],
  };

  // id word pools — combined into "adjective_noun" sprite_ids, filtered
  // against whatever's already taken at pick time. This is a large
  // combinatorial pool (adjectives × nouns), not a fixed list, so it comfortably
  // covers far more sprites than the game will ever have without repeating.
  const ID_ADJ = [
    "ancient", "mossy", "wandering", "sunlit", "hollow", "stormy", "quiet",
    "golden", "shifting", "salt", "ember", "frost", "twilight", "river",
    "coastal", "highland", "whispering", "tangled", "driftwood", "jagged",
    "hidden", "silver", "restless", "emerald", "dusk", "dawn", "wild",
    "lonely", "crumbling", "painted", "weathered", "gleaming", "shadow",
    "distant", "humble", "proud", "curious", "brisk", "smouldering",
    "brittle", "rusted", "sodden", "windswept", "hardy", "faded", "misty",
    "molten", "craggy", "sunken", "flickering",
  ];
  const ID_NOUN = {
    character: [
      "wanderer", "smith", "ranger", "weaver", "drifter", "scout", "elder",
      "apprentice", "guardian", "trader", "hunter", "sentinel", "herald",
      "keeper", "warden", "courier", "healer", "forager", "minstrel",
      "tinker", "fisher", "farmhand", "sailor", "scribe", "duelist",
      "lamplighter", "shepherd", "diver", "trapper", "falconer", "potter",
      "mercenary", "watchman", "dancer", "prospector", "harbourmaster",
    ],
    monster: [
      "stalker", "brute", "wraith", "lurker", "stag", "boar", "eel",
      "hound", "golem", "troll", "hag", "wyrm", "shade", "reaver",
      "gnasher", "crawler", "howler", "stomper", "prowler", "skulker",
      "grazer", "scuttler", "marauder", "sentinel", "gnawer", "snapper",
      "roamer", "creeper", "razorback", "bonewalker",
    ],
    object: [
      "lantern", "anvil", "cart", "fence", "loom", "kiln", "totem", "well",
      "bridge", "satchel", "cairn", "shrine", "signpost", "pier", "gate",
      "hearth", "firepit", "beehive", "millstone", "sundial", "watchtower",
      "footbridge", "cellar", "dovecote", "stile", "waystone", "granary",
      "smokehouse", "windmill", "jetty",
    ],
    item: [
      "pendant", "vial", "hatchet", "cloak", "compass", "pouch", "fishhook",
      "flute", "map", "key", "arrowhead", "hat", "whistle", "teacup",
      "spool", "cape", "rune", "bracelet", "mortar", "bell", "letter",
      "marbles", "cup", "sundial", "top", "wire", "basket", "hairpin",
      "bottle", "charm",
    ],
  };

  function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }

  const lastPrompt = {};
  function pickPrompt(bank, key) {
    let p = pick(bank);
    if (bank.length > 1) { let tries = 0; while (p === lastPrompt[key] && tries++ < 8) p = pick(bank); }
    lastPrompt[key] = p;
    return p;
  }

  function randomId(kind, taken) {
    taken = taken || new Set();
    const fam = kind === "character" ? "character" : kind.startsWith("monster") ? "monster" : kind;
    const nouns = ID_NOUN[fam] || ID_NOUN.object;
    for (let i = 0; i < 80; i++) {
      const id = pick(ID_ADJ) + "_" + pick(nouns);
      if (!taken.has(id.toLowerCase())) return id;
    }
    // pool exhausted (shouldn't happen in practice) — numeric fallback
    const base = pick(ID_ADJ) + "_" + pick(nouns);
    let n = 2, id = base;
    while (taken.has(id.toLowerCase())) id = base + "_" + (n++);
    return id;
  }

  // kind: "character" | "monster:humanoid" | "monster:quadruped" | "object" |
  // "item" | "state". ctx: { baseName?, taken?: Set }. Returns { prompt, id }
  // — for kind "state", id is a short state/costume name, not a sprite id.
  function suggest(kind, ctx) {
    ctx = ctx || {};
    const bank = PROMPTS[kind] || PROMPTS.object;
    const prompt = pickPrompt(bank, kind);
    if (kind === "state") return { prompt, id: pickPrompt(PROMPTS.state_ids, "state_ids") };
    return { prompt, id: randomId(kind, ctx.taken) };
  }

  return { suggest };
})();
