// ===== Our RPG Workshop — static site builder (Phase 5) =====
// Assembles studio/dist/site/: a fully self-contained deployable copy of the
// Workshop — one prebuilt <script> bundle instead of ~150 dev <script> tags,
// pages generated in "site mode" (studio/tools/gen_pages.mjs --site), plus
// every asset the studio fetches at runtime. Any static host (Cloudflare
// Pages) can serve the result as-is: DEPLOY.md has the full deploy recipe.
//
// Layout mirrors dev exactly (js/game-shim.js's ASSET_BASE = STUDIO_ROOT +
// "../"): the site root holds assets/ (+ a slice of js/ the zone workers
// importScripts), the Workshop itself lives one level down at /workshop/.
//
//   node studio/tools/build_site.mjs [--tiles] [--out <dir>]
//
// --tiles   also copies the deep-zoom assets/zones/*_tiles directories
//           (~650MB — belongs on R2/CDN in production, excluded by default).
// --out     override the output directory (default: studio/dist/site).
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { execFileSync } from "child_process";
import { build } from "esbuild";

const STU = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REPO = path.resolve(STU, "..");

const argv = process.argv.slice(2);
const INCLUDE_TILES = argv.includes("--tiles");
const outFlagAt = argv.indexOf("--out");
const OUTDIR = path.resolve(outFlagAt >= 0 ? argv[outFlagAt + 1] : path.join(STU, "dist/site"));
const WORKSHOP = path.join(OUTDIR, "workshop");

const K = n => (n / 1024).toFixed(0) + "K";
const M = n => (n / (1024 * 1024)).toFixed(1) + "M";
let counts = {};                       // step label -> {files, bytes}
const tally = (label, files, bytes) => { counts[label] = { files, bytes }; };

console.log(`\n=== Our RPG Workshop site build ===`);
console.log(`out: ${OUTDIR}${INCLUDE_TILES ? "  (deep-zoom tiles INCLUDED — big!)" : ""}`);

// ---- 1. Preflight -----------------------------------------------------------
// The studio's bundled script list (js/page-loader.js) includes
// js/lua/lua-src-gen.js, which tools/build.mjs generates from
// js/lua/prelude.lua + scripts/**/*.lua and is gitignored (never in a fresh
// checkout). Bundling would otherwise silently ship without quests/dialogue.
const LUA_GEN = path.join(REPO, "js/lua/lua-src-gen.js");
if (!fs.existsSync(LUA_GEN)) {
  console.error(`\nMissing ${path.relative(REPO, LUA_GEN)} — run \`node tools/build.mjs\` first.`);
  process.exit(1);
}

fs.rmSync(OUTDIR, { recursive: true, force: true });
fs.mkdirSync(WORKSHOP, { recursive: true });

// ---- 2. Bundle: studio/js/page-loader.js's S list, concatenated + minified -
// Same load-order contract as dev (document.write in that exact order), same
// esbuild options as tools/build.mjs (classic scripts sharing one global
// scope — bundle:false, not modules). Entries are stored depth-1 relative to
// a studio page: "../js/X" -> studio/js/X, "../../js/X" -> repo js/X.
const loaderSrc = fs.readFileSync(path.join(STU, "js/page-loader.js"), "utf8");
const entries = JSON.parse(loaderSrc.match(/var S = (\[[\s\S]*?\]);/)[1]);

function resolveEntry(entry) {
  const m = /^(\.\.\/)+/.exec(entry);
  if (!m) throw new Error(`page-loader entry has no leading "../": ${entry}`);
  const ups = m[0].length / 3, rest = entry.slice(m[0].length);
  if (ups === 1) return path.join(STU, rest);
  if (ups === 2) return path.join(REPO, rest);
  throw new Error(`Unexpected "../" depth (${ups}) in page-loader entry: ${entry}`);
}

let rawBytes = 0;
let combined = `/* studio/dist/site/workshop/dist/workshop-bundle.js — generated by\n` +
  ` * studio/tools/build_site.mjs from studio/js/page-loader.js's script list.\n` +
  ` * Classic scripts sharing one global scope (bundle:false) — same contract\n` +
  ` * as the dev page-loader and the game's own dist/bundle.js. */\n`;
for (const entry of entries) {
  const fp = resolveEntry(entry);
  const code = fs.readFileSync(fp, "utf8"); // throws loudly if a listed file is missing
  rawBytes += Buffer.byteLength(code);
  combined += `\n/* ${entry} */\n` + code + "\n;\n";
}

const result = await build({
  stdin: { contents: combined, loader: "js", resolveDir: REPO },
  bundle: false,
  minify: true,
  legalComments: "none",
  charset: "utf8",
  logLevel: "info",
  write: false,
});
const bundleOut = result.outputFiles[0].text;
const bundlePath = path.join(WORKSHOP, "dist/workshop-bundle.js");
fs.mkdirSync(path.dirname(bundlePath), { recursive: true });
fs.writeFileSync(bundlePath, bundleOut);
tally("bundle", entries.length, Buffer.byteLength(bundleOut));
console.log(`\nBundle: ${entries.length} scripts, raw ${K(rawBytes)} -> minified ${K(Buffer.byteLength(bundleOut))} -> ${path.relative(OUTDIR, bundlePath)}`);

// ---- 3. Pages: gen_pages.mjs --site <WORKSHOP> -----------------------------
// Spawned rather than imported: gen_pages.mjs is a top-level script (not a
// module export), and a child process gives it a clean process.argv without
// this script's own flags leaking in.
execFileSync(process.execPath, [path.join(STU, "tools/gen_pages.mjs"), "--site", WORKSHOP], {
  stdio: "inherit",
});

// ---- 4. Copy into <outdir>/workshop/ ---------------------------------------
// Generic recursive copy with a per-entry exclude predicate; every skip is
// logged (no silent omissions) and counted.
function copyTree(src, dest, { exclude = () => false, label } = {}) {
  let files = 0, bytes = 0;
  const skipped = [];
  const walk = (s, d, rel) => {
    const st = fs.statSync(s);
    if (st.isDirectory()) {
      if (exclude(rel, true)) { skipped.push(rel + "/"); return; }
      fs.mkdirSync(d, { recursive: true });
      for (const name of fs.readdirSync(s).sort()) walk(path.join(s, name), path.join(d, name), rel ? rel + "/" + name : name);
    } else {
      if (exclude(rel, false)) { skipped.push(rel); return; }
      fs.mkdirSync(path.dirname(d), { recursive: true });
      fs.copyFileSync(s, d);
      files++; bytes += st.size;
    }
  };
  if (!fs.existsSync(src)) { console.log(`  [${label}] source missing, nothing copied: ${path.relative(REPO, src)}`); return { files: 0, bytes: 0 }; }
  walk(src, dest, "");
  if (skipped.length) console.log(`  [${label}] excluded ${skipped.length}: ${skipped.slice(0, 8).join(", ")}${skipped.length > 8 ? ", …" : ""}`);
  tally(label, files, bytes);
  console.log(`  [${label}] ${files} files, ${K(bytes)} -> ${path.relative(OUTDIR, dest)}`);
  return { files, bytes };
}

console.log(`\nCopying studio assets:`);

// css/ — studio stylesheet, referenced by every generated page ({{ROOT}}css/studio.css)
copyTree(path.join(STU, "css"), path.join(WORKSHOP, "css"), { label: "css" });

// fonts/ — the two vendored OFL families studio.css @font-faces point at
// ("../fonts/…" relative to css/), so they live beside css/ in the site too.
copyTree(path.join(STU, "fonts"), path.join(WORKSHOP, "fonts"), { label: "fonts" });

// zone-worker.js + zone-chunk-worker.js: loaded via `new Worker(STUDIO_BASE +
// "js/zone-worker.js")` (studio/js/pages/zones.js:324,599), so they must land
// at <outdir>/workshop/js/ — the studio root in the deployed site.
const WORKERS = ["zone-worker.js", "zone-chunk-worker.js"];
fs.mkdirSync(path.join(WORKSHOP, "js"), { recursive: true });
for (const w of WORKERS) fs.copyFileSync(path.join(STU, "js", w), path.join(WORKSHOP, "js", w));
console.log(`  [workers] ${WORKERS.length} files -> workshop/js/`);

// Both workers importScripts() the game's REAL terrain/feature/chunk engine
// with paths relative to themselves ("../../js/…" from studio/js/ = repo
// js/…), so those exact source files have to exist one level ABOVE
// workshop/ in the site too (the ASSET_BASE root) — read from both worker
// files confirms this is the complete dependency set (no further nested
// importScripts inside them).
const WORKER_DEPS = [
  "data.js", "content.js",
  "world/terrain.js", "world/features.js", "world/erosion.js", "world/chunks.js",
];
let depFiles = 0, depBytes = 0;
for (const rel of WORKER_DEPS) {
  const src = path.join(REPO, "js", rel), dst = path.join(OUTDIR, "js", rel);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
  depFiles++; depBytes += fs.statSync(src).size;
}
tally("worker-deps", depFiles, depBytes);
console.log(`  [worker-deps] ${depFiles} files, ${K(depBytes)} -> ${path.relative(OUTDIR, path.join(OUTDIR, "js"))}/ (zone workers' importScripts targets)`);

// assets/zones/ — baked zone manifests/images (+ deep-zoom tiles with --tiles).
// index.json is skipped here: gen_pages --site (step 3, above) already wrote
// a freshly-computed one straight into the site output, and copying studio's
// own copy over it would risk clobbering it with a stale/absent dev-mode one.
copyTree(path.join(STU, "assets/zones"), path.join(WORKSHOP, "assets/zones"), {
  label: "assets/zones",
  exclude: (rel, isDir) => {
    if (isDir && /_tiles$/.test(path.basename(rel)) && !INCLUDE_TILES) return true;
    if (!isDir && rel === "index.json") return true;
    return false;
  },
});
// studio/zones/*.html: NOT copied — step 3 (gen_pages --site) already
// regenerates every zones/ page (hub + per-zone), same as every other tab.

// ---- 5. Copy into <outdir>/ (the ASSET_BASE root, one level above workshop/)
console.log(`\nCopying game assets (ASSET_BASE root):`);
for (const dir of ["sheets", "sfx", "ambience", "music", "birdsong"]) {
  copyTree(path.join(REPO, "assets", dir), path.join(OUTDIR, "assets", dir), { label: "assets/" + dir });
}

// ---- 6. Root redirect -------------------------------------------------------
// The site's actual app lives at /workshop/ (see the ASSET_BASE layout note
// up top); the bare domain root just bounces straight there.
fs.writeFileSync(path.join(OUTDIR, "index.html"), `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="0; url=./workshop/">
  <title>Our RPG Workshop</title>
  <link rel="canonical" href="./workshop/">
</head>
<body>
  <p>Redirecting to <a href="./workshop/">Our RPG Workshop</a>…</p>
  <script>location.replace("./workshop/");</script>
</body>
</html>
`);
console.log(`\n[redirect] wrote index.html -> ./workshop/`);

// ---- 7. Summary --------------------------------------------------------------
function dirSize(dir) {
  let bytes = 0, files = 0;
  if (!fs.existsSync(dir)) return { bytes, files };
  for (const name of fs.readdirSync(dir)) {
    const fp = path.join(dir, name), st = fs.statSync(fp);
    if (st.isDirectory()) { const s = dirSize(fp); bytes += s.bytes; files += s.files; }
    else { bytes += st.size; files++; }
  }
  return { bytes, files };
}
const total = dirSize(OUTDIR);
console.log(`\n=== Site summary ===`);
for (const [label, c] of Object.entries(counts)) console.log(`  ${label.padEnd(14)} ${String(c.files).padStart(5)} files  ${K(c.bytes).padStart(8)}`);
console.log(`  ${"TOTAL".padEnd(14)} ${String(total.files).padStart(5)} files  ${M(total.bytes).padStart(8)}`);
const tilesNote = INCLUDE_TILES ? " + deep-zoom tiles" : ", tiles excluded — pass --tiles to include";
const tree = [
  OUTDIR,
  "  index.html          (redirect -> workshop/)",
  "  assets/*            (sheets, sfx, ambience, music, birdsong)",
  "  js/*                (zone-worker importScripts targets only)",
  "  workshop/",
  "    index.html, <tab>/*, zones/*, sprites/*   (generated pages)",
  "    css/                (studio stylesheet)",
  "    js/                 (zone-worker.js, zone-chunk-worker.js)",
  "    dist/workshop-bundle.js   (everything else, prebuilt)",
  "    assets/zones/       (baked zone data" + tilesNote + ")",
].join("\n");
console.log("\n" + tree + "\n");
