// Regenerates the studio's multi-page HTML shell:
//   • studio/index.html          → the Home dashboard (kind "home", lives AT the studio root)
//   • profile/index.html         → the signed-in Profile hub (kind "profile", not a top-nav tab)
//   • <tab>/index.html           → the tab hub (folder names match the tab labels)
//   • <tab>/<slug(key)>.html     → one page per detail item in that tab
//   • sprites/<slug(key)>.html   → one sprite (art) page per character/object/monster
//   • edit/, zones/npc, skills/skill → the few genuinely dynamic (param) pages
//
// The item keys come from tools/items-index.json (regenerate that with the
// headless enumerator when the game data changes). Run from anywhere:
//   node studio/tools/gen_pages.mjs
import fs from "fs"; import path from "path";
import { splitGroups } from "./bundle-groups.mjs";
const STU = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const IDX = JSON.parse(fs.readFileSync(path.join(STU, "tools/items-index.json"), "utf8"));

// Phase 5: `--site <outdir>` emits the same pages into a standalone static
// site build (studio/tools/build_site.mjs) instead of the studio tree
// itself — the site loads one prebuilt dist/workshop-bundle.js instead of
// the dev page-loader, and nothing under studio/ is touched. Plain
// `node gen_pages.mjs` (no flag) is byte-identical to before.
const siteFlagAt = process.argv.indexOf("--site");
const SITE_OUT = siteFlagAt >= 0 ? path.resolve(process.argv[siteFlagAt + 1] || "") : null;
const OUT_ROOT = SITE_OUT || STU;
fs.mkdirSync(OUT_ROOT, { recursive: true });

// MUST match Nav.slugKey in js/page-shell.js
const slug = k => String(k == null ? "" : k).replace(/[^A-Za-z0-9._$-]/g, "_");

// keep js/page-loader.js's baked script list (only rewrite it if it exists) —
// dev-mode only; the site build ships prebuilt bundles instead (see page()).
if (!SITE_OUT) {
  const loaderList = JSON.parse(fs.readFileSync(path.join(STU, "js/page-loader.js"), "utf8").match(/var S = (\[[\s\S]*?\]);/)[1]);
  const { home: HOME_LIST, gamedata: GD_LIST } = splitGroups(loaderList);
  fs.writeFileSync(path.join(STU, "js/page-loader.js"),
`// AUTO-GENERATED by tools/gen_pages.mjs — do not edit by hand.
// Pulls in the studio data layer + render code, then the multi-page shell.
// document.write during initial parse keeps external scripts executing in order.
// Paths are stored depth-1 ("../js/…" studio, "../../js/…" repo); STUDIO_ROOT is
// the real hop to the studio root for THIS page, so we swap the leading "../"
// for it — pages nested deeper (npc/<snake>/…) then resolve correctly.
//
// The Home page (kind "home") boots on the SLIM list (no game data layer, no
// heavy content renderers) for a fast first paint, then js/pages/home.js pulls
// the game data in the background off window.__LAZY_GAMEDATA to light up the
// census + frieze. Every other page loads the full list S. Groups are derived
// from S in studio/tools/bundle-groups.mjs so they can't drift.
(function () {
  var R = window.STUDIO_ROOT || "../";
  function resolve(e) { return R + e.replace(/^\\.\\.\\//, ""); }
  var S = ${JSON.stringify(loaderList, null, 2)};
  var HOME = ${JSON.stringify(HOME_LIST, null, 2)};
  var GAMEDATA = ${JSON.stringify(GD_LIST, null, 2)};
  var kind = (window.STUDIO_PAGE || {}).kind;
  if (kind === "home") window.__LAZY_GAMEDATA = GAMEDATA.map(resolve);
  var LIST = kind === "home" ? HOME : S;
  for (var i = 0; i < LIST.length; i++) document.write('<script src="' + resolve(LIST[i]) + '"><\\/script>');
})();
`);
}

const iconTag = "<link rel=\"icon\" href=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='18' fill='%23060a08'/%3E%3Cpath d='M20 44 Q42 20 60 30 T92 22' stroke='%238f7ef0' stroke-width='5' fill='none' opacity='.55' stroke-linecap='round'/%3E%3Cpath d='M10 62 Q34 34 54 46 T94 38' stroke='%2356e39f' stroke-width='8' fill='none' stroke-linecap='round'/%3E%3Cpath d='M6 80 Q36 54 60 64 T96 58' stroke='%233ec6c0' stroke-width='5' fill='none' opacity='.75' stroke-linecap='round'/%3E%3Crect x='74' y='10' width='6' height='6' fill='%23eae4d2'/%3E%3Crect x='24' y='16' width='4' height='4' fill='%23eae4d2' opacity='.7'/%3E%3C/svg%3E\">";
// Per-page boot scripts. Dev always loads js/page-loader.js (it self-selects
// the slim/full list by kind). The site build ships prebuilt chunk bundles, so
// Home gets the slim workshop-home.js + a window.__LAZY_GAMEDATA pointer to the
// game-data chunk it pulls in the background; every other page gets the full
// workshop-bundle.js. (Groups: studio/tools/bundle-groups.mjs.)
const bootScripts = cfg => {
  if (!SITE_OUT) return `<script src="{{ROOT}}js/page-loader.js"></script>`;
  if (cfg && cfg.kind === "home")
    return `<script>window.__LAZY_GAMEDATA = ["{{ROOT}}dist/workshop-gamedata.js"];</script>\n  <script src="{{ROOT}}dist/workshop-home.js"></script>`;
  return `<script src="{{ROOT}}dist/workshop-bundle.js"></script>`;
};
const page = (title, cfg) =>
`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title ? "Our RPG Workshop — " + title : "Our RPG Workshop"}</title>
  ${iconTag}
  <link rel="stylesheet" href="{{ROOT}}css/studio.css">
</head>
<body>
  <noscript><p style="padding:2rem">Our RPG Workshop needs JavaScript.</p></noscript>
  <script>window.STUDIO_ROOT = "{{ROOT}}"; window.STUDIO_PAGE = ${JSON.stringify(cfg)};</script>
  ${bootScripts(cfg)}
</body>
</html>
`;
// {{ROOT}} = the relative hop from THIS page up to the studio root. Pages nested
// deeper (e.g. npc/<snake>/template.html) need more "../" than the depth-1 tab
// pages, so resolve it per file from the output path.
const write = (rel, content) => {
  const fp = path.join(OUT_ROOT, rel);
  const depth = rel.split("/").length - 1;          // folders above the file
  const root = "../".repeat(depth);
  fs.mkdirSync(path.dirname(fp), { recursive: true });
  fs.writeFileSync(fp, content.split("{{ROOT}}").join(root));
};

// wipe every managed folder (old route-name folders + new tab-name folders)
const MANAGED = ["player","npc","players","npcs","sprites","world-objects","objects","monsters","biomes","tiles","items","ui","procgen","map","zones","quests","ideas","code","sounds","triggers","skills","review","needs-art","settings","profile","edit"];
for (const d of MANAGED) fs.rmSync(path.join(OUT_ROOT, d), { recursive: true, force: true });

// tab hubs — folder name = slug of the tab label
const HUBS = [
  ["player",        "Player",        { kind:"catalog", tab:"player",        type:"character", roster:"player", title:"Players" }],
  ["npc",           "NPC",           { kind:"npclist", tab:"npc" }],
  ["sprites",       "Sprites",       { kind:"sprites", tab:"sprites" }],
  ["world-objects", "World Objects", { kind:"catalog", tab:"world-objects", type:"object" }],
  ["monsters",      "Monsters",      { kind:"catalog", tab:"monsters",      type:"monster" }],
  ["biomes",        "Biomes",        { kind:"catalog", tab:"biomes",        type:"tile" }],
  ["items",         "Items",         { kind:"catalog", tab:"items",         type:"ui" }],
  ["procgen",       "Procgen",       { kind:"catalog", tab:"procgen",       type:"map" }],
  ["zones",         "Zones",         { kind:"zones",   tab:"zones" }],
  ["quests",        "Quests",        { kind:"quests",  tab:"quests" }],
  ["ideas",         "Ideas",         { kind:"ideas",   tab:"ideas" }],
  ["code",          "Code",          { kind:"code",    tab:"code" }],
  ["bugs",          "Bugs",          { kind:"bugs",    tab:"bugs" }],
  ["sounds",        "Sounds",        { kind:"catalog", tab:"sounds",        type:"sound" }],
  ["skills",        "Skills",        { kind:"skills",  tab:"skills" }],
  ["review",        "Review",        { kind:"review",  tab:"review" }],
  ["needs-art",     "Needs art",     { kind:"needs-art", tab:"needs-art" }],
  ["settings",      "Settings",      { kind:"settings",tab:"settings" }],
  // Profile isn't a top-nav tab (STUDIO_TABS) — it's reached from the signed-in
  // "@username" chip — but it's a hub page like any other, same pattern as Settings.
  ["profile",       "Profile",       { kind:"profile", tab:"profile" }],
];
for (const [folder, label, cfg] of HUBS) write(`${folder}/index.html`, page(label, cfg));

let count = 0, collisions = 0;
const seen = {};   // folder → Set(slug) collision guard
const idOf = e => e.itemId || e.snake || e.key;   // name-based id where available (MUST match Nav.idOf)
// fileId → the page's filename (slug of the id); cfg.key stays the real lookup key
const emit = (folder, fileId, title, cfg) => {
  const s = slug(fileId), set = (seen[folder] = seen[folder] || new Set());
  if (set.has(s)) { collisions++; return; }
  set.add(s);
  write(`${folder}/${s}.html`, page(title, cfg));
  count++;
};

// instance / detail pages — one per catalog item, named by its id.
// Players → player/<snake>.html. NPCs are "template" characters: they live in a
// per-sprite folder npc/<snake>/, whose template.html is the character page and
// whose <shire>$<zone>.html siblings are that sprite's baked instances (below).
for (const c of IDX.character) {
  if (c.npc) emit("npc/" + slug(idOf(c)), "template", c.name || c.key, { kind:"detail", tab:"npc", type:"character", key:c.key });
  else emit("player", idOf(c), c.name || c.key, { kind:"detail", tab:"player", type:"character", key:c.key });
}
for (const o of IDX.object)   emit("world-objects", idOf(o), o.name || o.key, { kind:"detail", tab:"world-objects", type:"object", key:o.key });
for (const m of IDX.monster)  emit("monsters", idOf(m), m.name || m.key, { kind:"detail", tab:"monsters", type:"monster", key:m.key });
for (const t of IDX.tile)     emit("biomes",  idOf(t), t.name || t.key, { kind:"detail", tab:"biomes", type:"tile", key:t.key });
for (const u of IDX.ui)       emit("items",   idOf(u), u.name || u.key, { kind:"detail", tab:"items", type:"ui", key:u.key });
for (const p of IDX.map)      emit("procgen", idOf(p), p.name || p.key, { kind:"detail", tab:"procgen", type:"map", key:p.key });
for (const sd of IDX.sound)   emit("sounds",  idOf(sd), sd.name || sd.key, { kind:"detail", tab:"sounds", type:"sound", key:sd.key });
for (const sk of IDX.skills)  emit("skills",  sk, sk, { kind:"skill", tab:"skills", key:sk });
// world-baked NPC detail pages — one static page per baked NPC instance, keyed by
// its full id (spriteSnake$shire$zone, e.g. "zik.emory$almtharop$0.0"), so links to
// a baked NPC are clean static URLs instead of npc/npc.html?zone=&id=. The zone is
// the id's LAST "$" segment ("0.0" → "0,0"); npc/npc.html below stays as a
// positional/name-only fallback. Filenames carry "$" so they never clash with the
// character-catalog NPC pages above (which are named by bare sprite snake).
for (const zn of (IDX.zonenpc || [])) {
  if (!zn || !zn.id) continue;
  const parts = String(zn.id).split("$");                    // [spriteSnake, shire, zoneDot]
  const rest = parts.slice(1).join("$");                     // "eanflood$0.0"
  const zone = parts[parts.length - 1].replace(".", ",");    // "0,0"
  emit("npc/" + slug(parts[0]), rest, zn.name || zn.id, { kind: "npc", tab: "npc", zone, id: zn.id });
}
// Quest DETAIL is dynamic (query-driven) — see the dynamic quests/quest.html below.

// sprite (art) pages — one per character/object/monster (any of these can be linked)
for (const c of IDX.character) emit("sprites", idOf(c), c.name || c.key, { kind:"sprite", tab:"sprites", type:"character", key:c.key });
for (const o of IDX.object)   emit("sprites", idOf(o), o.name || o.key, { kind:"sprite", tab:"sprites", type:"object", key:o.key });
for (const m of IDX.monster)  emit("sprites", m.baseKey || m.key, m.name || m.key, { kind:"sprite", tab:"sprites", type:"monster", key:m.baseKey || m.key });   // one sprite page per base (deduped)
for (const u of IDX.ui)       emit("sprites", u.iconKey || idOf(u), u.name || u.key, { kind:"sprite", tab:"sprites", type:"ui", key:u.key });   // item icons on the Sprites tab, keyed by icon (deduped, no clash with object ids)
// biome tiles → Sprites tab: ONE page per biome, filename = biome name in
// snake_case (deep_sea, plains…), matching the tile provider's entry.snake.
const biomeSlug = n => String(n).replace(/\s*·.*$/, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
const _tileSeen = new Set();
for (const t of IDX.tile) {
  const m = /^bg_(\d+)_\d+$/.exec(t.key);
  if (m) { if (_tileSeen.has(m[1])) continue; _tileSeen.add(m[1]); emit("sprites", biomeSlug(t.name), t.name || t.key, { kind:"sprite", tab:"sprites", type:"tile", key:t.key }); }
  else emit("sprites", idOf(t), t.name || t.key, { kind:"sprite", tab:"sprites", type:"tile", key:t.key });
}
for (const p of IDX.map)      emit("sprites", idOf(p), p.name || p.key, { kind:"sprite", tab:"sprites", type:"map", key:p.key });    // map icons → Sprites tab

// per-zone static pages — one per BAKED zone manifest (zone_<zx>_<zy>.json), e.g.
// zones/0.0.html — plus a baked-zone index the NPC/Quests tabs aggregate across.
const bakedZoneList = [];
try {
  for (const f of fs.readdirSync(path.join(STU, "assets/zones"))) {
    const m = /^zone_(-?\d+)_(-?\d+)\.json$/.exec(f);
    if (!m) continue;
    emit("zones", m[1] + "." + m[2], "Zone " + m[1] + "," + m[2], { kind:"zones", tab:"zones", zx: Number(m[1]), zy: Number(m[2]) });
    bakedZoneList.push(m[1] + "," + m[2]);
  }
} catch (_) {}
// Written to OUT_ROOT (not STU) in site mode, since studio/ itself must stay
// untouched there — build_site.mjs copies assets/zones/ into the site
// afterwards, at which point this freshly-computed index.json is already there.
try {
  const zonesOut = path.join(OUT_ROOT, "assets/zones");
  fs.mkdirSync(zonesOut, { recursive: true });
  fs.writeFileSync(path.join(zonesOut, "index.json"), JSON.stringify(bakedZoneList));
} catch (_) {}

// genuinely-dynamic param pages (drafts / positional / community + zone NPC/quest detail)
write("edit/index.html",      page("Editor", { kind:"editor", tab:"player" }));
write("skills/skill.html",    page("Skill",  { kind:"skill",  tab:"skills" }));   // ?draft= / ?pid= fallback
write("npc/npc.html",         page("NPC",    { kind:"npc",     tab:"npc" }));      // ?zone=&id=&at= — any baked zone
write("quests/quest.html",    page("Quest",  { kind:"quests",  tab:"quests" }));   // ?id=&zone= — any baked zone

// the Home dashboard — lives AT the studio root, not one folder under it like
// every other page, so STUDIO_ROOT is "./" rather than a computed "../" hop.
fs.writeFileSync(path.join(OUT_ROOT, "index.html"), page("", { kind: "home" }).split("{{ROOT}}").join("./"));

console.log("hubs:", HUBS.length, "| per-item pages:", count, "| slug collisions skipped:", collisions);
